# Retail Sales Performance Analytics

In [ ]:
## Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
## Load Dataset
df = pd.read_csv("/content/superstore.csv", engine='python')
df.head(5)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [ ]:
## Data Understanding
df.shape

(51290, 27)

In [ ]:
df.dtypes

Category           object
City               object
Country            object
Customer.ID        object
Customer.Name      object
Discount          float64
Market             object
记录数                 int64
Order.Date         object
Order.ID           object
Order.Priority     object
Product.ID         object
Product.Name       object
Profit            float64
Quantity            int64
Region             object
Row.ID              int64
Sales               int64
Segment            object
Ship.Date          object
Ship.Mode          object
Shipping.Cost     float64
State              object
Sub.Category       object
Year                int64
Market2            object
weeknum             int64
dtype: object

In [ ]:
# Check year range

print(df['Year'].min())
print(df['Year'].max())

2011
2014

In [ ]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [ ]:
## Data Cleaning
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [ ]:
## Exploratory Data Analysis
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [ ]:
# Step 4: Data Understanding and Data Cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#checking duplicate values
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(51290, 27)

In [ ]:
# removing extra spaces
df.columns = df.columns.str.strip()
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

# STEP 5 – Feature Engineering

In [ ]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [ ]:
# Convert date into proper date format

df['Order.Date'] = pd.to_datetime(df['Order.Date'])
df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

In [ ]:
df.dtypes

Category                  object
City                      object
Country                   object
Customer.ID               object
Customer.Name             object
Discount                 float64
Market                    object
记录数                        int64
Order.Date        datetime64[ns]
Order.ID                  object
Order.Priority            object
Product.ID                object
Product.Name              object
Profit                   float64
Quantity                   int64
Region                    object
Row.ID                     int64
Sales                      int64
Segment                   object
Ship.Date         datetime64[ns]
Ship.Mode                 object
Shipping.Cost            float64
State                     object
Sub.Category              object
Year                       int64
Market2                   object
weeknum                    int64
dtype: object

In [ ]:
# Create Month column
# .dt is used to get date details like month, year, day and quarter

df['Month'] = df['Order.Date'].dt.month_name()

In [ ]:
# Create year column
df['Year'] = df['Order.Date'].dt.year

In [ ]:
# Create Day Name column
# Used to analyze which day receives the highest number of orders

df['Day'] = df['Order.Date'].dt.day_name()

In [ ]:
# Get quarter from date
# Q1=Jan-Mar, Q2=Apr-Jun, Q3=Jul-Sep, Q4=Oct-Dec

df['Quarter'] = df['Order.Date'].dt.quarter

In [ ]:
# Calculate delivery days
# Find days between order and shipping

df['Shipping Days'] = (df['Ship.Date'] - df['Order.Date']).dt.days

In [ ]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum', 'Month', 'Day', 'Quarter',
       'Shipping Days'],
      dtype='object')

#  Step 6 : Exploratory Data Analysis (EDA)

In [ ]:
# Total sales
total_sales = df['Sales'].sum()
print("Total Sales :", total_sales)

# Total profit
total_profit = df['Profit'].sum()
print("Total Profit :", total_profit)

# Total orders
total_orders = df['Order.ID'].nunique()
print("Total Orders :", total_orders)

# Total customers
total_customers = df['Customer.ID'].nunique()
print("Total Customers :", total_customers)

# Calculate average sales
average_sales = df['Sales'].mean()
print("Average Sales :", round(average_sales,2))

# Find highest sale
highest_sale = df['Sales'].max()
print("Highest Sale :", highest_sale)

# Find lowest sale
lowest_sale = df['Sales'].min()
print("Lowest Sale :", lowest_sale)

Total Sales : 12642905
Total Profit : 1467457.2912800002
Total Orders : 25035
Total Customers : 4873
Average Sales : 246.5
Highest Sale : 22638
Lowest Sale : 0

# Step 7 : Data Visualization

In [ ]:
# Group sales by month

monthly_sales = df.groupby('Month')['Sales'].sum()
monthly_sales

# Explanation:
# groupby() groups all same months together.
# sum() adds the sales of each month.
# This shows total sales for every month.

# Business Use:
# Helps identify which month has the highest and lowest sales.

Month
April         698603
August       1293852
December     1580816
February      543768
January       675141
July          749423
June         1269751
March         770519
May           904061
November     1551319
October      1168220
September    1437432
Name: Sales, dtype: int64

In [ ]:
# Monthly sales chart

monthly_sales_df = monthly_sales.reset_index()

fig = px.line(
    monthly_sales_df,
    x='Month',
    y='Sales',
    title='Monthly Sales Trend'
)

fig.show()

In [ ]:
# Group sales by category

category_sales = df.groupby('Category')['Sales'].sum()
category_sales

# Explanation:
# Groups all categories together.
# Calculates total sales of each category.

# Business Use:
# Helps identify the best-selling category.

Category
Furniture          4110884
Office Supplies    3787330
Technology         4744691
Name: Sales, dtype: int64

In [ ]:
# Category chart

fig = px.bar(
    x=category_sales.index,
    y=category_sales.values,
    title="Sales by Category"
)

fig.show()

# Explanation:
# x shows category names.
# y shows total sales.
# This chart compares sales of each category.

# Business Use:
# Helps find the best-selling category.

In [ ]:
# Group sales by product

top_products = df.groupby('Product.Name')['Sales'].sum()

# Sort products by sales

top_products = top_products.sort_values(ascending=False)

# Show top 10 products

top_products = top_products.head(10)

top_products

# Explanation:
# Groups sales for each product.
# Sorts products from highest to lowest sales.
# Displays the top 10 products.

# Business Use:
# Helps identify the company's best-selling products.

Product.Name
Apple Smart Phone, Full Size                                86936
Cisco Smart Phone, Full Size                                76441
Motorola Smart Phone, Full Size                             73159
Nokia Smart Phone, Full Size                                71904
Canon imageCLASS 2200 Advanced Copier                       61600
Hon Executive Leather Armchair, Adjustable                  58200
Office Star Executive Leather Armchair, Adjustable          50667
Harbour Creations Executive Leather Armchair, Adjustable    50120
Samsung Smart Phone, Cordless                               48654
Nokia Smart Phone, with Caller ID                           47880
Name: Sales, dtype: int64

In [ ]:
# Product chart

fig = px.bar(
    x=top_products.index,
    y=top_products.values,
    title="Top 10 Products by Sales"
)

fig.show()

# Explanation:
# x = Product names
# y = Total sales
# Bar chart compares the sales of the top 10 products.

# Business Use:
# Helps identify the best-selling products.
# Company can focus on these products to increase revenue.

# Step 8 : Business Insights

In [ ]:
# Region sales

region_sales = df.groupby('Region')['Sales'].sum()

region_sales

# Explanation:
# Groups data by region.
# Adds total sales of each region.
# Shows which region has the highest sales.

# Business Use:
# Helps identify the best-performing region.

Region
Africa             783776
Canada              66932
Caribbean          324281
Central           2822399
Central Asia       752839
EMEA               806184
East               678834
North             1248192
North Asia         848349
Oceania           1100207
South             1600960
Southeast Asia     884438
West               725514
Name: Sales, dtype: int64

In [ ]:
fig = px.bar(
    x = region_sales.index,
    y = region_sales.values,
    title = "Sales by Region"
)

fig.show()

# Explanation:
# x = Region names
# y = Total sales
# Bar chart compares the sales of each region.

# Business Use:
# Helps identify the best-performing region.
#

In [ ]:
# Category profit

category_profit = df.groupby('Category')['Profit'].sum()

category_profit

# Explanation:
# Groups data by category.
# Adds total profit of each category.
# Shows which category earns the most profit.

# Business Use:
# Helps identify the most profitable category.

Category
Furniture          285204.72380
Office Supplies    518473.83430
Technology         663778.73318
Name: Profit, dtype: float64

In [ ]:
# Profit chart

fig = px.bar(
    x=category_profit.index,
    y=category_profit.values,
    title="Profit by Category"
)

fig.show()

# Explanation:
# x = Category names
# y = Total profit
# Bar chart compares profit across categories.

# Business Use:
# Helps decide which category should be promoted.

Central